#!/bin/sh

## Make symbolic links

ln -s $PWD/after $HOME/.vim/after

ln -s $HOME/.vim/bundle/wmgraphviz.vim/ftdetect/dot.vim $PWD/after/ftdetect/dot.vim
ln -s $HOME/.vim/bundle/wmgraphviz.vim/ftplugin/dot.vim $PWD/after/ftplugin/dot.vim

ln -s $HOME/.vim/bundle/plantuml-syntax/ftdetect/plantuml.vim $PWD/after/ftdetect/plantuml.vim
ln -s $HOME/.vim/bundle/plantuml-syntax/ftplugin/plantuml.vim $PWD/after/ftplugin/plantuml.vim
